version: '3.8'

services:
  php_app_shoppingcart:
    build:
      context: etc/infrastructure/php
      dockerfile: Dockerfile
    container_name: php_app_shoppingcart
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9001:9000
    depends_on:
      - mysql_shoppingcart

  nginx_server_shoppingcart:
    image: nginx:latest
    container_name: nginx_server_shoppingcart
    ports:
      - 8000:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/Symfony/public/:/app/apps/Symfony/public
    depends_on:
      - php_app_shoppingcart

  mysql_shoppingcart:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWD}
    ports:
    - 3306:3306
    expose:
      - 3306
    volumes:
    - ./var/MySQL:/var/lib/mysql

