product_retrieve_one:
  path: /products/{id}
  controller: SymfonyApp\Controller\Shop\ProductController::retrieveOne
  methods: [GET]

product_retrieve_all:
  path: /products/
  controller: SymfonyApp\Controller\Shop\ProductController::retrieveAll
  methods: [GET]

product_create:
  path: /products
  controller: SymfonyApp\Controller\Shop\ProductController::create
  methods: [POST]
