product_retrieve_one:
  path: /products/{id}
  controller: SymfonyApp\Controller\Shop\ProductController::retrieveOne
  methods: [GET]

product_create:
  path: /products
  controller: SymfonyApp\Controller\Shop\ProductController::create
  methods: [POST]
