cart_retrieve_one:
  path: /carts/{id}
  controller: SymfonyApp\Controller\Shop\Cart\RetrieveOneCartController
  methods: [GET]

cart_retrieve_all:
  path: /carts/
  controller: SymfonyApp\Controller\Shop\Cart\RetrieveAllCartsController
  methods: [GET]

cart_create:
  path: /carts
  controller: SymfonyApp\Controller\Shop\Cart\CreateCartController
  methods: [POST]

add_product_to_cart:
  path: /carts/{cartId}/items
  controller: SymfonyApp\Controller\Shop\Cart\AddProductToCartController
  methods: [POST]
